openapi: 3.0.0
info:
  title: Create Prompt API endpoint
  version: '2023-10-31'
paths:
  /api/elastic_assistant/prompts:
    post:
      operationId: CreatePrompt
      x-codegen-enabled: true
      description: Create a prompt
      summary: Create a prompt
      tags:
        - Prompt API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptCreateProps'
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptResponse'
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  error:
                    type: string
                  message:
                    type: string
  
  /api/elastic_assistant/prompts/{id}:
    get:
      operationId: ReadPrompt
      x-codegen-enabled: true
      description: Read a single prompt
      summary: Read a single prompt
      tags:
        - Prompts API
      parameters:
        - name: id
          in: path
          required: true
          description: The prompt's `id` value.
          schema:
            type: string
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptResponse'
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  error:
                    type: string
                  message:
                    type: string
    put:
      operationId: UpdatePrompt
      x-codegen-enabled: true
      description: Update a single prompt
      summary: Update a single prompt
      tags:
        - Prompt API
      parameters:
        - name: id
          in: path
          required: true
          description: The prompt's `id` value.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptUpdateProps'
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptResponse'
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  error:
                    type: string
                  message:
                    type: string
    delete:
      operationId: DeletePrompt
      x-codegen-enabled: true
      description: Deletes a single prompt using the `id` field.
      summary: Deletes a single prompt
      tags:
        - Prompt API
      parameters:
        - name: id
          in: path
          required: true
          description: The prompt's `id` value.
          schema:
            type: string
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptResponse'
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                  error:
                    type: string
                  message:
                    type: string

components:
  schemas:
    PromptCreateProps:
      type: object
      description: AI assistant create prompt settings.
      required:
        - 'content'
        - 'name'
        - 'promptType'
      properties:
        content:
          type: string
          description: Prompt content.
        name:
          type: string
          description: Prompt name.
        promptType:
          type: string
          description: Prompt type.
        isDefault:
          description: Is default prompt.
          type: boolean
        isShared:
          description: Is shared prompt.
          type: boolean
        isNewConversationDefault:
          description: Is default prompt.
          type: boolean
    
    PromptUpdateProps:
      type: object
      description: AI assistant update prompt settings.
      properties:
        content:
          type: string
          description: Prompt content.
        name:
          type: string
          description: Prompt name.
        promptType:
          type: string
          description: Prompt type.
        isShared:
          description: Is shared prompt.
          type: boolean
        isNewConversationDefault:
          description: Is default prompt.
          type: boolean

    PromptResponse:
      type: object
      description: AI assistant prompt.
      required:
        - 'timestamp'
        - 'content'
        - 'role'
        - 'id'
      properties:
        id:
          type: string
        content:
          type: string
          description: Prompt content.
        name:
          type: string
          description: Prompt name.
        promptType:
          type: string
          description: Prompt type.
        isDefault:
          description: Is default prompt.
          type: boolean
        isShared:
          description: Is shared prompt.
          type: boolean
        isNewConversationDefault:
          description: Is default prompt.
          type: boolean
        updatedAt:
          description: The last time prompt was updated.
          type: string
        createdAt:
          description: The last time prompt was updated.
          type: string
        updatedBy:
          description: User who was updated prompt.
          type: string
        createdBy:
          description: User who was created prompt.
          type: string
