openapi: 3.0.0
info:
  title: Common Conversation Attributes
  version: 'not applicable'
paths: {}
components:
  x-codegen-enabled: true
  schemas:
    NonEmptyString:
      type: string
      pattern: ^(?! *$).+$
      minLength: 1
      description: A string that is not empty and does not contain only whitespace

    UUID:
      type: string
      format: uuid
      description: A universally unique identifier

    User:
      type: object
      description: Could be any string, not necessarily a UUID
      properties:
        id:
          type: string
          description: User id.
        name:
          type: string
          description: User name.

    MessagePresentation:
      type: object
      description: Could be any string, not necessarily a UUID
      properties:
        delay:
          type: integer
          description: Could be any string, not necessarily a UUID
        stream:
          type: boolean
          description: Could be any string, not necessarily a UUID

    TraceData:
      type: object
      description: trace Data
      properties:
        transactionId:
          type: string
          description: Could be any string, not necessarily a UUID
        traceId:
          type: string
          description: Could be any string, not necessarily a UUID

    Replacement:
      type: object
      additionalProperties: true

    Reader:
      type: object
      additionalProperties: true

    Provider:
      type: string
      description: Provider
      enum:
        - OpenAI
        - Azure OpenAI

    MessageRole:
      type: string
      description: Message role.
      enum:
        - system 
        - user
        - assistant

    Message:
      type: object
      description: AI assistant conversation message.
      required:
        - 'timestamp'
        - 'content'
        - 'role'
      properties:
        content:
          type: string
          description: Message content.
        reader:
          $ref: '#/components/schemas/Reader'
          description: Message content.
        replacements:
          $ref: '#/components/schemas/Replacement'
        role:
          $ref: '#/components/schemas/MessageRole'
          description: Message role.
        timestamp:
          $ref: '#/components/schemas/NonEmptyString'
          description: The timestamp message was sent or received.         
        isError:
          type: boolean
          description: Is error message.
        presentation:
          $ref: '#/components/schemas/MessagePresentation'
          description: ID of the exception container
        traceData:
          $ref: '#/components/schemas/TraceData'
          description: trace Data

    ApiConfig:
      type: object
      properties:
        connectorId:
          type: string
          description: connector Id
        connectorTypeTitle:
          type: string
          description: connector Type Title
        defaultSystemPromptId:
          type: string
          description: defaultSystemPromptId
        provider:
          $ref: '#/components/schemas/Provider'
          description: Provider
        model:
          type: string
          description: model 

    ErrorSchema:
      type: object
      required:
        - error
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        error:
          type: object
          required:
            - status_code
            - message
          properties:
            status_code:
              type: integer
              minimum: 400
            message:
              type: string

    ConversationResponse:
      type: object
      required:
        - id
        - title
        - createdAt
        - user
        - namespace
        - apiConfig
      properties:
        id:
          oneOf:
            - $ref: '#/components/schemas/UUID'
            - $ref: '#/components/schemas/NonEmptyString'
        title:
          type: string
          description: The conversation title.
        'timestamp':
          $ref: '#/components/schemas/NonEmptyString'
        updatedAt:
          description: The last time conversation was updated.
          type: string
        createdAt:
          description: The last time conversation was updated.
          type: string
        replacements:
          $ref: '#/components/schemas/Replacement'
        user:
          $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
              $ref: '#/components/schemas/Message'
          description: The conversation messages.
        apiConfig:
          $ref: '#/components/schemas/ApiConfig'
          description: LLM API configuration.
        isDefault:
          description: Is default conversation.
          type: boolean
        excludeFromLastConversationStorage:
          description: excludeFromLastConversationStorage.
          type: boolean
        namespace:
          type: string
          description: Kibana space

    ConversationUpdateProps:
      type: object
      required:
        - id
      properties:
        id:
          oneOf:
            - $ref: '#/components/schemas/UUID'
            - $ref: '#/components/schemas/NonEmptyString'
        title:
          type: string
          description: The conversation title.
        messages:
          type: array
          items:
              $ref: '#/components/schemas/Message'
          description: The conversation messages.
        apiConfig:
          $ref: '#/components/schemas/ApiConfig'
          description: LLM API configuration.
        excludeFromLastConversationStorage:
          description: excludeFromLastConversationStorage.
          type: boolean
        replacements:
          $ref: '#/components/schemas/Replacement'

    ConversationCreateProps:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: The conversation title.
        messages:
          type: array
          items:
              $ref: '#/components/schemas/Message'
          description: The conversation messages.
        apiConfig:
          $ref: '#/components/schemas/ApiConfig'
          description: LLM API configuration.
        isDefault:
          description: Is default conversation.
          type: boolean
        excludeFromLastConversationStorage:
          description: excludeFromLastConversationStorage.
          type: boolean
        replacements:
          $ref: '#/components/schemas/Replacement'
    
    ConversationMessageCreateProps:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
              $ref: '#/components/schemas/Message'
          description: The conversation messages.

